version: '3.1'
services:

  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
      - ./vhost:/etc/nginx/vhost.d

  nginx-proxy-acme:
    container_name: nginx-proxy-acme
    environment:
      DEFAULT_EMAIL: mail@yourdomain.tld
      NGINX_PROXY_CONTAINER: nginx-proxy
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
      - ./vhost:/etc/nginx/vhost.d
    restart: unless-stopped
